theme: jekyll-theme-cayman
title: DFG-SPP 1962 Fall School on \n Optimization under Uncertainty
description: Uncertainty Quantification and Stochastic Optimization of Complex Systems 
show_downloads: true
google_analytics:

github:
  zip_url: http://example.com/download.zip
  is_project_page: https://forms.gle/79AZXzHgRkXN3b8E6
