theme: jekyll-theme-cayman
title: DFG-SPP 1962 Summer School on Optimization under Uncertainty
description: September 8-10, 2021 from 13:00 - 18:00 (CEST) 
show_downloads: true
google_analytics:

github:
  zip_url: http://example.com/download.zip
  is_project_page: https://forms.gle/79AZXzHgRkXN3b8E6
