theme: jekyll-theme-cayman
title: | 
DFG-SPP 1962 Fall School
Optimization under Uncertainty
September 8-10, 2021 (virtual)
description: Uncertainty Quantification and Stochastic Optimization of Complex Systems 
show_downloads: true
google_analytics:

github:
  zip_url: http://example.com/download.zip
  is_project_page: https://forms.gle/79AZXzHgRkXN3b8E6
