theme: jekyll-theme-cayman
title: SPP 1962 Fall School on Optimization under Uncertainty
description: Uncertainty Quantification and Stochastic Optimization of Complex Systems 
show_downloads: true
google_analytics:
is_project_page: true
