theme: jekyll-theme-cayman
title: SPP 1962 Autumn School on Optimization under Uncertainty
description: Uncertainty Quantification and Stochastic Optimization of Complex Systems (Supported by the DFG Priority Program 1962)
show_downloads: true
google_analytics:

github:
  zip_url: http://example.com/download.zip
  is_project_page: https://forms.gle/79AZXzHgRkXN3b8E6
